services:
  webapp:
    build:
      context: ../
      dockerfile: 02-Deserialisation_Advanced/Dockerfile
    ports:
      - "80:80"
    develop:
      watch:
        - action: sync
          path: ./code
          target: /usr/share/nginx/html
